[admin]
DB_HOST = 'localhost'
DB_PORT = 5432

DB_NAME = 'postgres'
DB_USER = 'postgres'
DB_PASS = 'postgres'

[user]
DB_HOST = 'localhost'
DB_PORT = 5432

DB_NAME = 'detected_cases'
DB_USER = 'covid_user'
DB_PASS = 'covid_pass'
