[admin]
DB_HOST = 'localhost'
DB_PORT = 5432

DB_NAME = 'postgres'
DB_USER = 'postgres'
DB_PASS = 'postgres'

[user]
DB_HOST = 'localhost'
DB_PORT = 5432

DB_NAME = 'test_covid_db'
DB_USER = 'test_covid_user'
DB_PASS = 'test_covid_pass'
